version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_app
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - 8000
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork


networks:
  mynetwork: