services:
  django_app:
    build:
      context: .
    container_name: django_app
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - 8000
    networks:
      - mynetwork
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - mynetwork
    restart: always

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app    
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - mynetwork
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:80"
    depends_on:
      - django_app
    networks:
      - mynetwork

networks:
  mynetwork: