# Generated by Django 4.2.16 on 2025-01-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE NONCLUSTERED INDEX idx_instrument_id
            ON history_history (instrument_id);
            """
        ),
    ]