# Generated by Django 4.2.16 on 2025-01-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_history_history_his_instrum_e6925d_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recent_update_date_time", models.DateTimeField()),
            ],
        ),
    ]
