# Generated by Django 4.2.16 on 2025-02-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.BigIntegerField()),
                ("high", models.BigIntegerField()),
                ("low", models.BigIntegerField()),
                ("close", models.BigIntegerField()),
                ("volume", models.BigIntegerField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.instrument",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            """
            CREATE NONCLUSTERED INDEX idx_instrument_id
            ON forcast_prediction (instrument_id);
            """
        ),        
    ]
